### ISSUE TITLE
chameleon projector allows things with hands to speak

### ISSUE THREAD

**Issue by Everturning** [Fansana/floofstation1#394]
# Description

Recently I was a thief and I didn't wanna be so I gave chaos items to a scug. On teaching the guy how to use it,  when it tried to talk, I could understand, to our mutual shock

# Reproduction
>be scug, or smth that doesn't speak english
have hands
>take chameleon projector and use it on object
>since you are no longer the funny stormrealm creature (I think it's this bc it uses polymorph) you >can speak common language
>budget babel book

# Expected behavior

>Use chameleon projector as no speaking thing
>Not able to speak common language

**Comment by Mnemotechnician** [comment]
Not a bug; however this behavior was changed upstream, awaiting an upstream merge.

**Comment by Everturning** [comment]
ah when I checked with an admin ingame they said it was a bug

**Comment by Mnemotechnician** [comment]
It certainly is an undesired behavior however, and it has been changed in https://github.com/Simple-Station/Einstein-Engines/pull/1223

**Comment by Everturning** [comment]
alr closing
