### ISSUE TITLE
new tool sounds are too loud. 

### ISSUE THREAD

**Issue by Fansana** [Fansana/floofstation1#43]
The tool sounds as well as the pick up sounds for items are too loud compared to everything else.

**Comment by therealDLondon** [comment]
Yes, exactly this, I have hyperacusis and these new sounds are making playing on this server near impossible, they're so loud and jarring and I should not have to reduce my entire game's volume.
They need to be on a seperate slider or toggle, and not tied to the master volume slider.

Terrible for accessability

**Comment by FoxxoTrystan** [comment]
Solved: https://github.com/Fansana/floofstation1/pull/91
