### ISSUE TITLE
Listening Post Operative role don't work

### ISSUE THREAD

**Issue by Fansana** [Fansana/floofstation1#46]
![image](https://github.com/user-attachments/assets/ecb3a75e-87a9-4dc2-a1a0-6efb1133a323)

**Comment by ShatteredSwords** [comment]
From what I have seen it "works" now, the playtime requirement was either reduced or disabled now.

**Comment by FoxxoTrystan** [comment]
Solved during an upstream merge, check requirement if its needs to be edited.
